# Generated by Django 5.2.16 on 2026-08-05 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('CUSTOM', 'Custom')], default='BIRTHDAY', max_length=20)),
                ('notes_for_ai', models.TextField(blank=True, help_text="Notes for AI generation (e.g., 'loves poetry')")),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'Family,Close')", max_length=255)),
                ('google_event_id', models.CharField(blank=True, help_text='ID from Google Contacts/Calendar', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_access_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('google_refresh_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('subscription_tier', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ELITE', 'Elite')], default='FREE', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField()),
                ('language', models.CharField(default='EN', max_length=10)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent')], default='GENERATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishes', to='greetify.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
