# Generated by Django 5.2.3 on 2026-08-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_contact_id',
            field=models.CharField(blank=True, help_text='ID from Google Contacts (People API)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='ID from Google Calendar', max_length=255, null=True),
        ),
    ]
