# Generated by Django 5.2.3 on 2026-08-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0002_event_google_contact_id_alter_event_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apple_user_id',
            field=models.CharField(blank=True, help_text="Apple ID 'sub' claim", max_length=255, null=True, unique=True),
        ),
    ]
