# Generated by Django 5.2.16 on 2026-08-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='Birthday', max_length=50),
        ),
    ]
