# Generated by Django 5.2.16 on 2026-08-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_number',
            field=models.CharField(blank=True, help_text='WhatsApp or phone number', max_length=20, null=True),
        ),
    ]
