# Generated by Django 5.2.16 on 2026-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0006_event_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="URL to the person's profile picture", null=True),
        ),
    ]
