# Generated by Django 5.2.3 on 2026-08-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0007_event_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('APP', 'App'), ('GOOGLE_CALENDAR', 'Google Calendar'), ('GOOGLE_CONTACTS', 'Google Contacts')], default='APP', max_length=50),
        ),
    ]
