# Generated by Django 5.2.3 on 2026-08-13 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0008_event_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishhistory',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='greetify.event'),
        ),
    ]
