# Generated by Django 5.2.3 on 2026-08-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0009_alter_wishhistory_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='apple_contact_id',
            field=models.CharField(blank=True, help_text='ID from Apple Contacts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='apple_event_id',
            field=models.CharField(blank=True, help_text='ID from Apple Calendar', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('APP', 'App'), ('GOOGLE_CALENDAR', 'Google Calendar'), ('GOOGLE_CONTACTS', 'Google Contacts'), ('APPLE_CALENDAR', 'Apple Calendar'), ('APPLE_CONTACTS', 'Apple Contacts')], default='APP', max_length=50),
        ),
    ]
