# Generated by Django 5.2.16 on 2026-08-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0010_event_apple_contact_id_event_apple_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_provider',
            field=models.CharField(default='APP', max_length=20),
        ),
    ]
