# Generated by Django 5.0.4 on 2026-09-07 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0012_deletedeventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='relationship',
            field=models.CharField(blank=True, help_text='Relationship to the user (e.g., Friend, Mother)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='greetify.event')),
            ],
        ),
    ]
