# Generated by Django 5.2.16 on 2026-09-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetify', '0013_event_relationship_eventnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='synced_contacts',
            field=models.JSONField(blank=True, default=list, help_text='Stores a lightweight JSON list of synced phone contacts'),
        ),
    ]
